name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - biotite=0.30.0
  - pip:
    - bio==1.3.2
    - icn3dpy==3.3.1
    - pandas==1.3.4
    - git+git://github.com/williamgilpin/pypdb
