name: notebook
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.7.3
  - anyio=3.3.2
  - argcomplete=1.12.3
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - biotite=0.30.0
  - bleach=4.1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.2
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - certipy=0.1.3
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - cryptography=3.4.7
  - cycler=0.11.0
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - greenlet=1.1.2
  - idna=3.1
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - importlib_resources=5.2.2
  - ipykernel=6.4.1
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=4.0.1
  - jupyter-offlinenotebook=0.2.1
  - jupyter-resource-usage=0.6.0
  - jupyter_client=7.0.6
  - jupyter_core=4.8.1
  - jupyter_server=1.11.1
  - jupyter_telemetry=0.1.0
  - jupyterhub-base=1.4.2
  - jupyterhub-singleuser=1.4.2
  - jupyterlab=3.1.17
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - jupyterlab_widgets=1.0.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mako=1.1.5
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - msgpack-python=1.0.2
  - nbclassic=0.3.2
  - nbclient=0.5.4
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - notebook=6.3.0
  - nteract_on_jupyter=2.1.3
  - numpy=1.21.3
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pamela=1.0.0
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.2.4
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pycurl=7.44.1
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.2
  - python-json-logger=2.0.1
  - python_abi=3.7
  - pytz=2021.3
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.26.0
  - requests-unixsocket=0.2.0
  - ruamel.yaml=0.17.16
  - ruamel.yaml.clib=0.2.2
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.2.0
  - six=1.16.0
  - sniffio=1.2.0
  - sqlalchemy=1.4.25
  - sqlite=3.36.0
  - terminado=0.12.1
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.0
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - bio==1.3.2
    - biopython==1.79
    - biothings-client==0.2.6
    - icn3dpy==3.3.1
    - idisplay==0.1.2
    - jupyter==1.0.0
    - jupyter-console==6.4.0
    - mygene==3.2.2
    - pandas==1.3.4
    - git+git://github.com/williamgilpin/pypdb
    - qtconsole==5.1.1
    - qtpy==1.11.2
    - tqdm==4.62.3
